//users
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const SET_AUTHED_USER = 'SET_AUTHED_USER'
export const LOGOUT_AUTHED_USER = 'LOGOUT_AUTHED_USER'
//questions
export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS'
export const ANSWER_QUESTION = 'ANSWER_QUESTION'
export const ADD_QUESTION = 'ADD_QUESTION'